### PR TITLE
showed crosschain rewards

### PR DESCRIPTION
**Pull request by smartdevcom**
Peek 2023-01-05 19-34

### CODE REVIEW

**Comment by carlomazzaferro** [comment]
1) Can we have just a Switch to <chain icon> instead of the chain name? As is, it doesn't look too good

Screenshot 2023-01-05 at 09 47 47

2) It is not showing all the rewards. I'm on moonbeam, but it is only showing the BSC rewards. But I also have Moonbeam rewards: 

Screenshot 2023-01-05 at 09 50 11

**Comment by peetzweg** [comment]
Using the abbreviated network name might help relief the crunched button label. We have the name afaik, we are using it in the tabs:

Screenshot 2023-01-09 at 10 07 56

**Comment by smartdevcom** [comment]
> Using the abbreviated network name might help relief the crunched button label. We have the name afaik, we are using it in the tabs:
> 
> Screenshot 2023-01-09 at 10 07 56

Fixed 
image

**Comment by peetzweg** [comment]
> > Using the abbreviated network name might help relief the crunched button label. We have the name afaik, we are using it in the tabs:
> > Screenshot 2023-01-09 at 10 07 56
> 
> Fixed image

Thats epic! will test it out right now.

**Comment by peetzweg** [comment]
Can we make these buttons plain buttons with the network icon? This split is a bit confusing as only the "Claim" part can be clicked. So no need to make it a more complex button than usual.

demo

**Comment by smartdevcom** [comment]
> Can we make these buttons plain buttons with the network icon? This split is a bit confusing as only the "Claim" part can be clicked. So no need to make it a more complex button than usual.
> 
> demo [ demo ](https://user-images.githubusercontent.com/839848/211777371-589ad006-6727-43f7-8463-8ae7d3691497.gif) [ ](https://user-images.githubusercontent.com/839848/211777371-589ad006-6727-43f7-8463-8ae7d3691497.gif)



> Can we make these buttons plain buttons with the network icon? This split is a bit confusing as only the "Claim" part can be clicked. So no need to make it a more complex button than usual.
> 
> demo [ demo ](https://user-images.githubusercontent.com/839848/211777371-589ad006-6727-43f7-8463-8ae7d3691497.gif) [ ](https://user-images.githubusercontent.com/839848/211777371-589ad006-6727-43f7-8463-8ae7d3691497.gif)

image
Fixed

**Comment by peetzweg** [comment]
If rewards are claimed, the value is not refreshed.

Let's remove the claimed rewards from the list of the modal. A refresh is not needed it's fine if it's only refreshed when revisting the site.

This will be a better experience than refreshing for the actual value, as people have been complaining that not everything was claimed. It looks like this if we immediately refresh after claiming, because rewards are accrued on a block basis and new rewards are already accrued most likely after claiming. So removing is a bit better, so people have the experience they have claimed "everything".

https://user-images.githubusercontent.com/839848/211781093-bdf0cfa4-a8c2-4667-bbfb-1b259061194d.mov

**Comment by peetzweg** [comment]
Claiming all rewards is not very transparent right now.
Everything is loading and not shown which one is currently claiming. Claimed rewards are not removed from the list on success. Furthermore it the total claiming process aborts for me each time after 2-3 successful claims.

**Let's remove the "claim all" button for now.** It's quite complex logic. And optimize it in a separate PR. Which than adds something similar as the transaction modals for the funding operations with each step individual and information. Will create a new ticket for it.

https://user-images.githubusercontent.com/839848/211789158-361811df-4fe2-4efe-a688-53bdd65e5ee2.mov

**Comment by peetzweg** [comment]
This button animation flickers, is it rerendering without a purpose? 🤔 
Can you fix this?

demo2

**Pull request merged**
