### PR TITLE
added performance fee

### PR DESCRIPTION
**Pull request by smartdevcom**
image

### CODE REVIEW

**Comment by carlomazzaferro** [comment]
LG, but let's add a tooltip explaining what the performance fee is

**Comment by carlomazzaferro** [comment]
"The fee taken by Midas Capital, as a percentage of the rewards earned by this strategy"

**Review by carlomazzaferro — CHANGES_REQUESTED** [review]
Add tooltip

**Comment by smartdevcom** [comment]
> Add tooltip

image

**Review by carlomazzaferro — APPROVED** [review]

**Pull request merged**
