### PR TITLE
added deprecated feature

### PR DESCRIPTION
**Pull request by smartdevcom**
image
image

### CODE REVIEW

**Comment by peetzweg** [comment]
Can we just not show this "Deprecated" filter at all, if there is no deprecated market visible to this user at all?

**Comment by smartdevcom** [comment]
> Can we just not show this "Deprecated" filter at all, if there is no deprecated market visible to this user at all?
> 
> Will only be confusing and it will best case never be needed anyways.

Done

**Comment by peetzweg** [comment]
Epic you even disabled the supply button 👍 

Screenshot 2022-09-26 at 17 35 17

**Comment by smartdevcom** [comment]
It's also disabled in modal

image

**Pull request merged**
