### PR TITLE
set supply caps

### PR DESCRIPTION
**Pull request by smartdevcom**
image

Now we can set `supply caps` in pool's admin page. And I am not sure if `Comptroller.supplyCaps()` returns value scaled by underlying decimals or 18. It seems to be scaled by underlying decimals. So pls focus more about it if you want to review. Also I didn't test it because all pools are in live and not sure which pool is proper to test. So Pls test it on your side properly and leave comments here. cc @carlomazzaferro @peetzweg

### CODE REVIEW

**Comment by carlomazzaferro** [comment]
> image
> 
> Now we can set `supply caps` in pool's admin page. And I am not sure if `Comptroller.supplyCaps()` returns value scaled by underlying decimals or 18. It seems to be scaled by underlying decimals. So pls focus more about it if you want to review. Also I didn't test it because all pools are in live and not sure which pool is proper to test. So Pls test it on your side properly and leave comments here. cc @carlomazzaferro @peetzweg

`Comptroller.supplyCaps()` does not use any scale. It is just the raw number of tokens that can be supplied at most. So no need to do any decimal weirdness.

**Comment by carlomazzaferro** [comment]
> > image
> > Now we can set `supply caps` in pool's admin page. And I am not sure if `Comptroller.supplyCaps()` returns value scaled by underlying decimals or 18. It seems to be scaled by underlying decimals. So pls focus more about it if you want to review. Also I didn't test it because all pools are in live and not sure which pool is proper to test. So Pls test it on your side properly and leave comments here. cc @carlomazzaferro @peetzweg
> 
> `Comptroller.supplyCaps()` does not use any scale. It is just the raw number of tokens that can be supplied at most. So no need to do any decimal weirdness.

There is also no problem of testing this on live pools, at least pools on NEON or Arbitrum. Because we can always set it to zero.

Isn't forking working btw? With forking you can test w/o making any damage

**Comment by smartdevcom** [comment]
> > > image
> > > Now we can set `supply caps` in pool's admin page. And I am not sure if `Comptroller.supplyCaps()` returns value scaled by underlying decimals or 18. It seems to be scaled by underlying decimals. So pls focus more about it if you want to review. Also I didn't test it because all pools are in live and not sure which pool is proper to test. So Pls test it on your side properly and leave comments here. cc @carlomazzaferro @peetzweg
> > 
> > 
> > `Comptroller.supplyCaps()` does not use any scale. It is just the raw number of tokens that can be supplied at most. So no need to do any decimal weirdness.
> 
> There is also no problem of testing this on live pools, at least pools on NEON or Arbitrum. Because we can always set it to zero.
> 
> Isn't forking working btw? With forking you can test w/o making any damage

makes sense, I will test it on forking

**Comment by smartdevcom** [comment]
> > > image
> > > Now we can set `supply caps` in pool's admin page. And I am not sure if `Comptroller.supplyCaps()` returns value scaled by underlying decimals or 18. It seems to be scaled by underlying decimals. So pls focus more about it if you want to review. Also I didn't test it because all pools are in live and not sure which pool is proper to test. So Pls test it on your side properly and leave comments here. cc @carlomazzaferro @peetzweg
> > 
> > 
> > `Comptroller.supplyCaps()` does not use any scale. It is just the raw number of tokens that can be supplied at most. So no need to do any decimal weirdness.
> 
> There is also no problem of testing this on live pools, at least pools on NEON or Arbitrum. Because we can always set it to zero.
> 
> Isn't forking working btw? With forking you can test w/o making any damage

Tested in forking BSC and it worked perfectly!

**Comment by carlomazzaferro** [comment]
Implementation looks good, will leave the UI details up to @peetzweg

**Review by peetzweg — APPROVED** [review]

**Comment by peetzweg** [comment]
lgtm

**Pull request merged**
