### PR TITLE
added plugin icons

### PR DESCRIPTION
**Pull request by smartdevcom**
image

### CODE REVIEW

**Comment by peetzweg** [comment]
Haha epic that was quick :) 
Does it fallback to the plugin emoji if not available?

**Comment by smartdevcom** [comment]
> Haha epic that was quick :) Does it fallback to the plugin emoji if not available?

Yes, it will show plug if icon doesn't exist

**Comment by peetzweg** [comment]
Cna you resolves these conflicts, than i'm happy to merge this 👍

**Review by peetzweg — APPROVED** [review]

**Comment by peetzweg** [comment]
Merging `development` now should also resolve the failed ci task.

**Pull request merged**
