### PR TITLE
improved loading skeleton

### PR DESCRIPTION
**Pull request by smartdevcom**
loading1

### CODE REVIEW

**Comment by peetzweg** [comment]
Looks good! Although, why is it initially so small, basically just showing pool details? THe Asset box is very thin. In the current version it's already a bigger size.

Can we improve this? Goal would be to have the least amount of jumping elements on the page.

**Comment by peetzweg** [comment]
So in the beginning it's briefly very small visible. Can't this already be a bit bigger? The Pool Details box is already big and shown at the top and than pushed down by the actual content of the page.

### T0
Screenshot 2022-11-07 at 12 05 19


### T1
Screenshot 2022-11-07 at 12 05 21

**Comment by peetzweg** [comment]
So many changes, I though it would only touch the skeleton haha. Bit scared to push it to production today. So maybe tomorrow :S

**Comment by smartdevcom** [comment]
> So many changes, I though it would only touch the skeleton haha. Bit scared to push it to production today. So maybe tomorrow :S

Another simple PR is here https://github.com/Midas-Protocol/monorepo/pull/975

**Comment by peetzweg** [comment]
We chose this implementation:
https://github.com/Midas-Protocol/monorepo/pull/975

**Pull request closed without merging**
