### PR TITLE
805 research replace apexcharts with react charts

### PR DESCRIPTION
**Pull request by smartdevcom**
image

image

I replaced `apexchart` with `recharts` which seems to be the best chart library for React. This chart can be customized. PR is ready. cc @peetzweg 

Preview: https://preview.midascapital.xyz/137/pool/1

### CODE REVIEW

**Comment by peetzweg** [comment]
Uh looks nice! So it's using the same color we are using for the Supply and Borrow APY columns font color?

**Comment by peetzweg** [comment]
Smart to add `preview`, just wanted to do it now haha, best feature :)

**Comment by smartdevcom** [comment]
> Uh looks nice! So it's using the same color we are using for the Supply and Borrow APY columns font color?

Yes, the same

**Comment by peetzweg** [comment]
Can we somehow elegantly add the `%` to the x and y axis values?
As well as a axis description? X-Axis => `Utilization`  and Y-Axis => `Rate`

**Comment by peetzweg** [comment]
This hover thing looks great. Maybe we can reduce the border radius and border widht a bit so it looks more like our other hover tooltips/popovers.

Screenshot 2022-10-12 at 11 46 00

**Comment by carlomazzaferro** [comment]
damn this looks good!

**Comment by smartdevcom** [comment]
All issues are fixed cc @peetzweg

**Comment by peetzweg** [comment]
The current utilization value should be shown on the graph.


Screenshot 2022-10-12 at 15 00 11

**Comment by peetzweg** [comment]
Looks good. Can we maybe cut the yaxis at 100%? So we get a slightly more resolution for the small values before the kink of the graph?
> 100% utilization should practically never happen.

**Comment by smartdevcom** [comment]
image

**Comment by peetzweg** [comment]
Can you maybe also prevent loading of the graph at all if the asset is protected?

demo

**Comment by peetzweg** [comment]
Looks good. Can we maybe cut the yaxis at 100%? So we get a slightly more resolution for the small values before the kink of the graph?
great than 100% utilization should practically never happen.

**Comment by smartdevcom** [comment]
image

like this?

**Comment by smartdevcom** [comment]
This is because supply and borrow rate will be higher than 100% when utilization is 100%, so `Rate` Y Axis limit is over 100, so if we cut off the YAxis then graph should be cut off as well, is it Okay?

**Comment by smartdevcom** [comment]
> Looks good. Can we maybe cut the yaxis at 100%? So we get a slightly more resolution for the small values before the kink of the graph? great than 100% utilization should practically never happen.

I only showed to 100% utilization I guess, you mean the rates?

**Comment by peetzweg** [comment]
> > Looks good. Can we maybe cut the yaxis at 100%? So we get a slightly more resolution for the small values before the kink of the graph? great than 100% utilization should practically never happen.
> 
> I only showed to 100% utilization I guess, you mean the rates?

Ah you are right, I wanted to cap the wrong thing. All good! 👍 🤦

**Pull request merged**
