### PR TITLE
fix issue with maxAmount calculation

### PR DESCRIPTION
**Pull request by dezine2dev**
## Description

Fix max withdraw issue and other potential rounding issue

## Type of change

- [ ] Docs change / dependency upgrade
- [ ] Configuration / tooling changes
- [ ] Refactoring
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires changes in customer code

## High-level change(s) description - from the user's perspective

The issue comes with managing max Amount. Current logic is converting fetched maxAmount big Number to string value and change that to big Number again on Confirm click. At this point there is tiny difference by rounding issue.
For max button case, we removed coverting process and use fetched maxAmount directly on final Confirm.

## Related Issue(s)

Fixes [the issue](https://github.com/Midas-Protocol/monorepo/issues/259)

### CODE REVIEW

**Review by carlomazzaferro — APPROVED** [review]

**Comment by carlomazzaferro** [comment]
LG, except failing CI

**Comment by smartdevcom** [comment]
I think it won't change even after converting twice. we use `formatUnits` and `parseUnits`. @dezine2dev  could you reproduce this kind of issue?
Like I tried `console.log(utils.parseUnits(utils.formatUnits('0x91929395471863899293')));` returns `0x91929395471863899293`

**Comment by dezine2dev** [comment]
> I think it won't change even after converting twice. we use `formatUnits` and `parseUnits`. @dezine2dev could you reproduce this kind of issue? Like I tried `console.log(utils.parseUnits(utils.formatUnits('0x91929395471863899293')));` returns `0x91929395471863899293`

Yes you are right. Double converting is not an issue but updateAmount function has a problem for handling maxAmount. 
```
 const bigAmount = utils.parseUnits(
      toFixedNoRound(Number(newAmount), tokenData?.decimals || DEFAULT_DECIMALS),
      tokenData?.decimals
    );
```
We are rounding fetched Maxamount at this line and it does not let us completely wipe out the max amount. I also see tiny more issues by this.
for example
- sometimes confirm button becomes disable after hitting max button due to max amount exceeding (from tiny difference)
- max repay has also tiny difference issue.

**Comment by smartdevcom** [comment]
We should round down the fetched amount because sometimes it exceeds 18 numbers under decimal point otherwise we get an error with `utils.parseUnits` and also the value which is rounded down should be smaller than real max amount so confirm button should not be disabled if max amount is correct.
@dezine2dev I am not sure which issue you faced but could you post a screenshot or video or whatever so I can fix that

**Comment by smartdevcom** [comment]
Done here https://github.com/Midas-Protocol/monorepo/pull/411

**Pull request closed without merging**
